apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ebs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0e5cfe954c2989427 
    fsType: ext4