apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ebs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0f98f5383f66e3850 
    fsType: ext4